language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"

env:
  - DJANGO=1.3.1
  - DJANGO=1.4
  - DJANGO=1.5.1

install:
    - pip install -q Django==$DJANGO --use-mirrors
    - python setup.py develop

script:  make test
