language: python

services:
  - redis-server

python:
  - "2.6"
  - "2.7"
  - "pypy"

env:
  - DJANGO="django==1.2.7"
  - DJANGO="django==1.3.1"
  - DJANGO="django==1.4"
  - DJANGO="django==1.5"
  - DJANGO="django==1.6"
  - DJANGO="git+https://github.com/django/django.git#egg=django"
  
matrix:
  include:
    - python: 3.2
      env: DJANGO=="django==1.5"
    - python: 3.3
      env: DJANGO=="django==1.5"
    - python: 3.4
      env: DJANGO=="django==1.5"
    - python: 3.2
      env: DJANGO=="django==1.6"
    - python: 3.3
      env: DJANGO=="django==1.6"
    - python: 3.4
      env: DJANGO=="django==1.6"
    - python: 3.2
      env: DJANGO=="git+https://github.com/django/django.git#egg=django"
    - python: 3.3
      env: DJANGO=="git+https://github.com/django/django.git#egg=django"
    - python: 3.4
      env: DJANGO=="git+https://github.com/django/django.git#egg=django"

install:
    - pip install -q $DJANGO --use-mirrors
    - python setup.py develop

script:  make test
